### ISSUE TITLE
String/Formatting examples

### ISSUE THREAD

**Issue by chipbell4** [MercerBinaryBears/ReferenceSheet#11]
String.format stuff

**Comment by TarkusLee** [comment]
Claimed? Python Cody

**Comment by TarkusLee** [comment]
The built in Python str and uni-code classes have a lot of good formatting, but custom formatting is found in class string.Formatter. 

Number Formatting:
The basic syntax for number formatting is `print("FORMAT".format(NUMBER));`
Examples: 
Number | Format | Output | What it did
3.141592|   {:.2f}   |   3.14      | 2 decimal places
1000000000 |    {:.2e}  |  1.00e+09 | Exponent notation

Here are a couple of example of basic string substitution, the {} is the placeholder for the substituted variables. If no format is specified, it will insert and format as a string.
`s1 = "so much depends upon {}".format("a red wheel barrow")`
`s2 = "glazed with {} water beside the {} chickens".format("rain", "white")`

You can also use the numeric position of the variables and change them in the strings, this gives some flexibility when doing the formatting, if you made a mistake in the order you can easily correct without shuffling all variables around.

`s1 = " {0} is better than {1} ".format("emacs", "vim")`
`s2 = " {1} is better than {0} ".format("emacs", "vim")`

The `str.format()` method and the Formatter class share the same syntax for format strings (although in the case of Formatter, subclasses can define their own format string syntax).

Format strings contain “replacement fields” surrounded by curly braces {}. Anything that is not contained in braces is considered literal text, which is copied unchanged to the output.
Basically the replacement field can start with a field_name that specifies the object whose value is to be formatted and inserted into the output instead of the replacement field.

Cool Custom Formatting Stuff:
`format(format_string, *args, **kwargs)`
Takes a format string and an arbitrary set of positional and keyword arguments. It is just a wrapper that calls `vformat()`.

`vformat(format_string, args, kwargs)`
This is basically the same as format() except it can take entire dictionaries of arguments for formatting. 

Examples of str.format():

```
'{0}, {1}, {2}'.format('a', 'b', 'c')
'a, b, c'
```

```
str = "Oh {0}, {0}! wherefore art thou {0}?".format("Romeo")
~~ Oh Romeo, Romeo! wherefore art thou Romeo?
```

Using type-specific formatting:

```
>>> import datetime
>>> d = datetime.datetime(2010, 7, 4, 12, 15, 58)
>>> '{:%Y-%m-%d %H:%M:%S}'.format(d)
'2010-07-04 12:15:58'
```
